server:
  port: 8053

spring:
  application:
    name: notification-service
  rabbitmq:
    username: oguz
    password: rabbitmqpass
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/