server:
  port: 8052

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: http://localhost:9411/

  rabbitmq:
    username: oguz
    password: rabbitmqpass
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue

  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/